version: '3.7'
services:
  redis:
    image: redis
    # command: ["redis-server", "--appendonly", "yes"]
    restart: always
    # ports:
    #   - 6379:6379
  
  api:
    build: .
    image: assignment-final-api
    restart: always
    ports:
      - 8000:8000
      # - 6380:6379
    links:
      - redis
    environment:
      MONGO_DATABASE: ${MONGO_DATABASE}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_HOST: mongodb
      MONGO_PORT: 27017x
      

  mongodb:
    image: mongo:latest
    restart: always
    volumes:
      - mongo-data:/data/db
      - ./db-init/:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}

  # docker-compose.yml
  # Add this top-level entry
  
  
volumes:
  mongo-data:


  